### ISSUE TITLE
Broken on Chrome 96

### ISSUE THREAD

**Issue by justinpenner** [o-t-w/color-font-palette#1]
This demo doesn't work for me in Chrome 96 on macOS Catalina, but I think I've found the cause. The user agent css is applying `font-weight: bold` to h2 elements, which seems to cause Bungee and Rocher to fall back to non-colour rendering.

![image](https://user-images.githubusercontent.com/46039243/143617588-4f06fe3e-b975-42a6-a52a-fcfbdc89b5b6.png)

Easy to fix with `h2 { font-weight: normal }`, which results in colour rendering:

![image](https://user-images.githubusercontent.com/46039243/143617749-dc14f8af-141f-4148-8629-7de036254456.png)

I'm also getting a blank white screen where the emoji font should be in the third demo, but I think that's simply due to [Chrome not supporting the OpenType-SVG format](https://pixelambacht.nl/chromacheck/) of that font.

**Comment by o-t-w** [comment]
I noticed this a while ago and had no idea how to fix it and it was really bugging me. Thanks for the fix! It's a shame color fonts are so temperamental.
I might remove the emoji font as Chrome has made it clear they will never support OpenType-SVG.
